name: boxch_extension
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hive_flutter: ^1.1.0
  countup: ^0.1.4
  http: ^0.13.4
  solana: ^0.29.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.6
  flutter_native_splash: ^2.2.14  #flutter pub run flutter_native_splash:create
  oktoast: ^3.2.0
  webview_flutter: ^3.0.4
  flutter_svg: ^1.1.6
  path_provider: ^2.0.13

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.2 #dart run build_runner build

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Aeroport
      fonts:
        - asset: assets/fonts/Aeroport.otf

flutter_native_splash:
      color: "#151A22"

